// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcsxjzyhnowprsdtmzog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjc3hqenlobm93cHJzZHRtem9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTQ5MzAsImV4cCI6MjA3MjUzMDkzMH0.68rotjizmw18i1Um6yfcznK3mSgZIFvzCpVOGru4Mls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});